# _config.yml
title: Kayleigh Browne
description: My Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

# Navigation menu
header_pages:
  - index.md
  - about.md
  - blog.md
